import type { Asset } from './Asset';
import type { Block } from './Block';
import type { Component } from './Component';
import type { Lesson } from './Lesson';
import type { Page } from './Page';

/**
 * Publisher-agnostic course root.
 * Future parsers (Rise, Storyline, Adapt, Word, PDF) must map into this shape.
 *
 * IDs are always taken from the source package — never generated by LMSBox.
 */
export interface Course {
  /** Source-supplied course id (Evolve: course.json _id) */
  id: string;
  title: string;
  displayTitle?: string;
  description?: string;
  body?: string;
  /** Publisher that produced this package */
  publisher: string;
  /** Top-level pages (Evolve contentObjects of type page / menu children) */
  pages: Page[];
  /** Flat index of all lessons (articles) for quick lookup */
  lessons: Lesson[];
  /** Flat index of all blocks */
  blocks: Block[];
  /** Flat index of all components */
  components: Component[];
  /** Flat index of all assets */
  assets: Asset[];
  /** Original course.json (or equivalent) payload — read-only debug aid */
  raw: Record<string, unknown>;
  /** Optional language / locale folder detected (e.g. "en") */
  locale?: string;
  /** Path prefix where course JSON was found (e.g. "course" or "course/en") */
  contentRoot: string;
}
